// Breakwater agent/replication wire contract.
// Frozen for M1 — additive changes only after this milestone.
// See PLAN.md → Transport & protocol.
//
// Append-only is structural: NO RPC on the agent port deletes, prunes, or
// mutates retention. Those exist only on the human-authenticated web/REST port.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: breakwater/v1/breakwater.proto

package breakwaterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED   JobType = 0
	JobType_JOB_TYPE_FILE_BACKUP   JobType = 1
	JobType_JOB_TYPE_IMAGE_BACKUP  JobType = 2
	JobType_JOB_TYPE_HYPERV_BACKUP JobType = 3
	JobType_JOB_TYPE_RESTORE       JobType = 4
	JobType_JOB_TYPE_UPDATE        JobType = 5 // prune/verify/replicate are server-side only — never dispatched to agents
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_FILE_BACKUP",
		2: "JOB_TYPE_IMAGE_BACKUP",
		3: "JOB_TYPE_HYPERV_BACKUP",
		4: "JOB_TYPE_RESTORE",
		5: "JOB_TYPE_UPDATE",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED":   0,
		"JOB_TYPE_FILE_BACKUP":   1,
		"JOB_TYPE_IMAGE_BACKUP":  2,
		"JOB_TYPE_HYPERV_BACKUP": 3,
		"JOB_TYPE_RESTORE":       4,
		"JOB_TYPE_UPDATE":        5,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_breakwater_v1_breakwater_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_breakwater_v1_breakwater_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{0}
}

type SnapshotKind int32

const (
	SnapshotKind_SNAPSHOT_KIND_UNSPECIFIED SnapshotKind = 0
	SnapshotKind_SNAPSHOT_KIND_FILE        SnapshotKind = 1
	SnapshotKind_SNAPSHOT_KIND_IMAGE       SnapshotKind = 2
	SnapshotKind_SNAPSHOT_KIND_HYPERV      SnapshotKind = 3
)

// Enum value maps for SnapshotKind.
var (
	SnapshotKind_name = map[int32]string{
		0: "SNAPSHOT_KIND_UNSPECIFIED",
		1: "SNAPSHOT_KIND_FILE",
		2: "SNAPSHOT_KIND_IMAGE",
		3: "SNAPSHOT_KIND_HYPERV",
	}
	SnapshotKind_value = map[string]int32{
		"SNAPSHOT_KIND_UNSPECIFIED": 0,
		"SNAPSHOT_KIND_FILE":        1,
		"SNAPSHOT_KIND_IMAGE":       2,
		"SNAPSHOT_KIND_HYPERV":      3,
	}
)

func (x SnapshotKind) Enum() *SnapshotKind {
	p := new(SnapshotKind)
	*p = x
	return p
}

func (x SnapshotKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotKind) Descriptor() protoreflect.EnumDescriptor {
	return file_breakwater_v1_breakwater_proto_enumTypes[1].Descriptor()
}

func (SnapshotKind) Type() protoreflect.EnumType {
	return &file_breakwater_v1_breakwater_proto_enumTypes[1]
}

func (x SnapshotKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotKind.Descriptor instead.
func (SnapshotKind) EnumDescriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{1}
}

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token format: BW1:<host:port>:<serverCertFP-sha256-hex>:<secret>
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Agent identity info (hostname, OS, agent version).
	AgentInfo *AgentInfo `protobuf:"bytes,2,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	// PEM-encoded self-signed client certificate (public half of agent keypair).
	ClientCertPem []byte `protobuf:"bytes,3,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetAgentInfo() *AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

func (x *EnrollRequest) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

type EnrollResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MachineId             string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`                                       // ULID
	HashingKey            []byte                 `protobuf:"bytes,2,opt,name=hashing_key,json=hashingKey,proto3" json:"hashing_key,omitempty"`                                    // per-repo hashing key only (never encryption keys)
	ServerCertFingerprint string                 `protobuf:"bytes,3,opt,name=server_cert_fingerprint,json=serverCertFingerprint,proto3" json:"server_cert_fingerprint,omitempty"` // confirmed pin
	// Default policy summary applied at enrollment (informational).
	PolicyId      string `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *EnrollResponse) GetHashingKey() []byte {
	if x != nil {
		return x.HashingKey
	}
	return nil
}

func (x *EnrollResponse) GetServerCertFingerprint() string {
	if x != nil {
		return x.ServerCertFingerprint
	}
	return ""
}

func (x *EnrollResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"` // e.g. "windows"
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"` // e.g. "amd64"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type AgentToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentToServer_Hello
	//	*AgentToServer_Heartbeat
	//	*AgentToServer_JobProgress
	//	*AgentToServer_JobResult
	//	*AgentToServer_Inventory
	Msg           isAgentToServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{3}
}

func (x *AgentToServer) GetMsg() isAgentToServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentToServer) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToServer) GetJobProgress() *JobProgress {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_JobProgress); ok {
			return x.JobProgress
		}
	}
	return nil
}

func (x *AgentToServer) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AgentToServer) GetInventory() *InventoryReport {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

type isAgentToServer_Msg interface {
	isAgentToServer_Msg()
}

type AgentToServer_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentToServer_JobProgress struct {
	JobProgress *JobProgress `protobuf:"bytes,3,opt,name=job_progress,json=jobProgress,proto3,oneof"`
}

type AgentToServer_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,4,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type AgentToServer_Inventory struct {
	Inventory *InventoryReport `protobuf:"bytes,5,opt,name=inventory,proto3,oneof"`
}

func (*AgentToServer_Hello) isAgentToServer_Msg() {}

func (*AgentToServer_Heartbeat) isAgentToServer_Msg() {}

func (*AgentToServer_JobProgress) isAgentToServer_Msg() {}

func (*AgentToServer_JobResult) isAgentToServer_Msg() {}

func (*AgentToServer_Inventory) isAgentToServer_Msg() {}

type ServerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerToAgent_HelloAck
	//	*ServerToAgent_JobStart
	//	*ServerToAgent_JobCancel
	//	*ServerToAgent_UpdateOffer
	//	*ServerToAgent_HeartbeatAck
	Msg           isServerToAgent_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{4}
}

func (x *ServerToAgent) GetMsg() isServerToAgent_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerToAgent) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerToAgent) GetJobStart() *JobStart {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_JobStart); ok {
			return x.JobStart
		}
	}
	return nil
}

func (x *ServerToAgent) GetJobCancel() *JobCancel {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_JobCancel); ok {
			return x.JobCancel
		}
	}
	return nil
}

func (x *ServerToAgent) GetUpdateOffer() *UpdateOffer {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_UpdateOffer); ok {
			return x.UpdateOffer
		}
	}
	return nil
}

func (x *ServerToAgent) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

type isServerToAgent_Msg interface {
	isServerToAgent_Msg()
}

type ServerToAgent_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerToAgent_JobStart struct {
	JobStart *JobStart `protobuf:"bytes,2,opt,name=job_start,json=jobStart,proto3,oneof"`
}

type ServerToAgent_JobCancel struct {
	JobCancel *JobCancel `protobuf:"bytes,3,opt,name=job_cancel,json=jobCancel,proto3,oneof"`
}

type ServerToAgent_UpdateOffer struct {
	UpdateOffer *UpdateOffer `protobuf:"bytes,4,opt,name=update_offer,json=updateOffer,proto3,oneof"`
}

type ServerToAgent_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,5,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

func (*ServerToAgent_HelloAck) isServerToAgent_Msg() {}

func (*ServerToAgent_JobStart) isServerToAgent_Msg() {}

func (*ServerToAgent_JobCancel) isServerToAgent_Msg() {}

func (*ServerToAgent_UpdateOffer) isServerToAgent_Msg() {}

func (*ServerToAgent_HeartbeatAck) isServerToAgent_Msg() {}

type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	MachineId    string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	AgentVersion string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Optional resume: last completed job step token.
	ResumeToken   string `protobuf:"bytes,3,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{5}
}

func (x *Hello) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Server may assign a session id for resume correlation.
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{6}
}

func (x *HelloAck) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HelloAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Heartbeat struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ClientTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	// Free disk on agent data volume, etc. (optional telemetry).
	FreeBytes     int64 `protobuf:"varint,2,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetClientTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTime
	}
	return nil
}

func (x *Heartbeat) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type JobStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type  JobType                `protobuf:"varint,2,opt,name=type,proto3,enum=breakwater.v1.JobType" json:"type,omitempty"`
	// Job-type-specific payload (JSON for flexibility in MVP).
	ParamsJson    []byte `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStart) Reset() {
	*x = JobStart{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStart) ProtoMessage() {}

func (x *JobStart) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStart.ProtoReflect.Descriptor instead.
func (*JobStart) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{9}
}

func (x *JobStart) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStart) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *JobStart) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

type JobCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCancel) Reset() {
	*x = JobCancel{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCancel) ProtoMessage() {}

func (x *JobCancel) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCancel.ProtoReflect.Descriptor instead.
func (*JobCancel) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{10}
}

func (x *JobCancel) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type JobProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BytesDone     int64                  `protobuf:"varint,2,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	BytesTotal    int64                  `protobuf:"varint,3,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"` // 0 if unknown
	Phase         string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Percent       uint32                 `protobuf:"varint,6,opt,name=percent,proto3" json:"percent,omitempty"` // 0-100, advisory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{11}
}

func (x *JobProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobProgress) GetBytesDone() int64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

func (x *JobProgress) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *JobProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *JobProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobProgress) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	BytesRead     int64                  `protobuf:"varint,4,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	BytesStored   int64                  `protobuf:"varint,5,opt,name=bytes_stored,json=bytesStored,proto3" json:"bytes_stored,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,6,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"` // set on success for backup jobs
	ResumeToken   string                 `protobuf:"bytes,7,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{12}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobResult) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *JobResult) GetBytesStored() int64 {
	if x != nil {
		return x.BytesStored
	}
	return 0
}

func (x *JobResult) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *JobResult) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type InventoryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeInfo          `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Vms           []*VMInfo              `protobuf:"bytes,2,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{13}
}

func (x *InventoryReport) GetVolumes() []*VolumeInfo {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *InventoryReport) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

type VolumeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // volume GUID or mount
	Mount         string                 `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"` // e.g. "C:\\"
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	FsType        string                 `protobuf:"bytes,4,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeInfo) Reset() {
	*x = VolumeInfo{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeInfo) ProtoMessage() {}

func (x *VolumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeInfo.ProtoReflect.Descriptor instead.
func (*VolumeInfo) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{14}
}

func (x *VolumeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VolumeInfo) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *VolumeInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *VolumeInfo) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RctCapable    bool                   `protobuf:"varint,3,opt,name=rct_capable,json=rctCapable,proto3" json:"rct_capable,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{15}
}

func (x *VMInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VMInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMInfo) GetRctCapable() bool {
	if x != nil {
		return x.RctCapable
	}
	return false
}

func (x *VMInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UpdateOffer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DownloadUrl      string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // relative path on :9443
	Ed25519Signature []byte                 `protobuf:"bytes,3,opt,name=ed25519_signature,json=ed25519Signature,proto3" json:"ed25519_signature,omitempty"`
	Mandatory        bool                   `protobuf:"varint,4,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateOffer) Reset() {
	*x = UpdateOffer{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOffer) ProtoMessage() {}

func (x *UpdateOffer) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOffer.ProtoReflect.Descriptor instead.
func (*UpdateOffer) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateOffer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateOffer) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdateOffer) GetEd25519Signature() []byte {
	if x != nil {
		return x.Ed25519Signature
	}
	return nil
}

func (x *UpdateOffer) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

type CheckContentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Content IDs as hex/opaque strings (kopia content ID format).
	ContentIds    []string `protobuf:"bytes,2,rep,name=content_ids,json=contentIds,proto3" json:"content_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckContentsRequest) Reset() {
	*x = CheckContentsRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckContentsRequest) ProtoMessage() {}

func (x *CheckContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckContentsRequest.ProtoReflect.Descriptor instead.
func (*CheckContentsRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{17}
}

func (x *CheckContentsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CheckContentsRequest) GetContentIds() []string {
	if x != nil {
		return x.ContentIds
	}
	return nil
}

type CheckContentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bitmap: bit i set ⇒ content_ids[i] already present. Packed little-endian bytes.
	PresentBitmap []byte `protobuf:"bytes,1,opt,name=present_bitmap,json=presentBitmap,proto3" json:"present_bitmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckContentsResponse) Reset() {
	*x = CheckContentsResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckContentsResponse) ProtoMessage() {}

func (x *CheckContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckContentsResponse.ProtoReflect.Descriptor instead.
func (*CheckContentsResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{18}
}

func (x *CheckContentsResponse) GetPresentBitmap() []byte {
	if x != nil {
		return x.PresentBitmap
	}
	return nil
}

type PutContentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Client-computed content ID; server re-computes and rejects mismatches.
	ContentId string `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Optional sequence for windowed acks.
	Seq           uint64 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentsRequest) Reset() {
	*x = PutContentsRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentsRequest) ProtoMessage() {}

func (x *PutContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentsRequest.ProtoReflect.Descriptor instead.
func (*PutContentsRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{19}
}

func (x *PutContentsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PutContentsRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *PutContentsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutContentsRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PutContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AckSeq        uint64                 `protobuf:"varint,1,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ContentId     string                 `protobuf:"bytes,4,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"` // server-confirmed ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutContentsResponse) Reset() {
	*x = PutContentsResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutContentsResponse) ProtoMessage() {}

func (x *PutContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutContentsResponse.ProtoReflect.Descriptor instead.
func (*PutContentsResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{20}
}

func (x *PutContentsResponse) GetAckSeq() uint64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *PutContentsResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PutContentsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PutContentsResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type PutTreeObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Serialized tree object (JSON; see pkg/format).
	TreeJson      []byte `protobuf:"bytes,2,opt,name=tree_json,json=treeJson,proto3" json:"tree_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTreeObjectRequest) Reset() {
	*x = PutTreeObjectRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTreeObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTreeObjectRequest) ProtoMessage() {}

func (x *PutTreeObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTreeObjectRequest.ProtoReflect.Descriptor instead.
func (*PutTreeObjectRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{21}
}

func (x *PutTreeObjectRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PutTreeObjectRequest) GetTreeJson() []byte {
	if x != nil {
		return x.TreeJson
	}
	return nil
}

type PutTreeObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTreeObjectResponse) Reset() {
	*x = PutTreeObjectResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTreeObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTreeObjectResponse) ProtoMessage() {}

func (x *PutTreeObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTreeObjectResponse.ProtoReflect.Descriptor instead.
func (*PutTreeObjectResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{22}
}

func (x *PutTreeObjectResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type PutImageManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ManifestJson  []byte                 `protobuf:"bytes,2,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutImageManifestRequest) Reset() {
	*x = PutImageManifestRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutImageManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutImageManifestRequest) ProtoMessage() {}

func (x *PutImageManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutImageManifestRequest.ProtoReflect.Descriptor instead.
func (*PutImageManifestRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{23}
}

func (x *PutImageManifestRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PutImageManifestRequest) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

type PutImageManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutImageManifestResponse) Reset() {
	*x = PutImageManifestResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutImageManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutImageManifestResponse) ProtoMessage() {}

func (x *PutImageManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutImageManifestResponse.ProtoReflect.Descriptor instead.
func (*PutImageManifestResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{24}
}

func (x *PutImageManifestResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type CommitSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          SnapshotKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=breakwater.v1.SnapshotKind" json:"kind,omitempty"`
	RootObjectId  string                 `protobuf:"bytes,3,opt,name=root_object_id,json=rootObjectId,proto3" json:"root_object_id,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	BytesRead     int64                  `protobuf:"varint,7,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	BytesStored   int64                  `protobuf:"varint,8,opt,name=bytes_stored,json=bytesStored,proto3" json:"bytes_stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitSnapshotRequest) Reset() {
	*x = CommitSnapshotRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSnapshotRequest) ProtoMessage() {}

func (x *CommitSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CommitSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{25}
}

func (x *CommitSnapshotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommitSnapshotRequest) GetKind() SnapshotKind {
	if x != nil {
		return x.Kind
	}
	return SnapshotKind_SNAPSHOT_KIND_UNSPECIFIED
}

func (x *CommitSnapshotRequest) GetRootObjectId() string {
	if x != nil {
		return x.RootObjectId
	}
	return ""
}

func (x *CommitSnapshotRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CommitSnapshotRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommitSnapshotRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *CommitSnapshotRequest) GetBytesRead() int64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *CommitSnapshotRequest) GetBytesStored() int64 {
	if x != nil {
		return x.BytesStored
	}
	return 0
}

type CommitSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ManifestRef   string                 `protobuf:"bytes,2,opt,name=manifest_ref,json=manifestRef,proto3" json:"manifest_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitSnapshotResponse) Reset() {
	*x = CommitSnapshotResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitSnapshotResponse) ProtoMessage() {}

func (x *CommitSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CommitSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{26}
}

func (x *CommitSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CommitSnapshotResponse) GetManifestRef() string {
	if x != nil {
		return x.ManifestRef
	}
	return ""
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{27}
}

func (x *GetSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Kind          SnapshotKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=breakwater.v1.SnapshotKind" json:"kind,omitempty"`
	RootObjectId  string                 `protobuf:"bytes,3,opt,name=root_object_id,json=rootObjectId,proto3" json:"root_object_id,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MachineId     string                 `protobuf:"bytes,6,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{28}
}

func (x *GetSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *GetSnapshotResponse) GetKind() SnapshotKind {
	if x != nil {
		return x.Kind
	}
	return SnapshotKind_SNAPSHOT_KIND_UNSPECIFIED
}

func (x *GetSnapshotResponse) GetRootObjectId() string {
	if x != nil {
		return x.RootObjectId
	}
	return ""
}

func (x *GetSnapshotResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetSnapshotResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetSnapshotResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{29}
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type GetObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{30}
}

func (x *GetObjectResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetContentRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // 0 = to end
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRangeRequest) Reset() {
	*x = GetContentRangeRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRangeRequest) ProtoMessage() {}

func (x *GetContentRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRangeRequest.ProtoReflect.Descriptor instead.
func (*GetContentRangeRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{31}
}

func (x *GetContentRangeRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetContentRangeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetContentRangeRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type GetContentRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRangeResponse) Reset() {
	*x = GetContentRangeResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRangeResponse) ProtoMessage() {}

func (x *GetContentRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRangeResponse.ProtoReflect.Descriptor instead.
func (*GetContentRangeResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{32}
}

func (x *GetContentRangeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // empty = caller's machine
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{33}
}

func (x *ListSnapshotsRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ListSnapshotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSnapshotsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*GetSnapshotResponse `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{34}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*GetSnapshotResponse {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListSnapshotsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListSnapshotsSinceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // source machine being mirrored
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`                        // opaque; empty = from beginning
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsSinceRequest) Reset() {
	*x = ListSnapshotsSinceRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsSinceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsSinceRequest) ProtoMessage() {}

func (x *ListSnapshotsSinceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsSinceRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsSinceRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{35}
}

func (x *ListSnapshotsSinceRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ListSnapshotsSinceRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSnapshotsSinceRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSnapshotsSinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*GetSnapshotResponse `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsSinceResponse) Reset() {
	*x = ListSnapshotsSinceResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsSinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsSinceResponse) ProtoMessage() {}

func (x *ListSnapshotsSinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsSinceResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsSinceResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{36}
}

func (x *ListSnapshotsSinceResponse) GetSnapshots() []*GetSnapshotResponse {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListSnapshotsSinceResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type CheckUpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion string                 `protobuf:"bytes,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	Channel        string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // edge|beta|stable
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckUpdateRequest) Reset() {
	*x = CheckUpdateRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateRequest) ProtoMessage() {}

func (x *CheckUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdateRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{37}
}

func (x *CheckUpdateRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *CheckUpdateRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type CheckUpdateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Available        bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Ed25519Signature []byte                 `protobuf:"bytes,3,opt,name=ed25519_signature,json=ed25519Signature,proto3" json:"ed25519_signature,omitempty"`
	SizeBytes        int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256Hex        string                 `protobuf:"bytes,5,opt,name=sha256_hex,json=sha256Hex,proto3" json:"sha256_hex,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckUpdateResponse) Reset() {
	*x = CheckUpdateResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateResponse) ProtoMessage() {}

func (x *CheckUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdateResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{38}
}

func (x *CheckUpdateResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckUpdateResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckUpdateResponse) GetEd25519Signature() []byte {
	if x != nil {
		return x.Ed25519Signature
	}
	return nil
}

func (x *CheckUpdateResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CheckUpdateResponse) GetSha256Hex() string {
	if x != nil {
		return x.Sha256Hex
	}
	return ""
}

type DownloadUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadUpdateRequest) Reset() {
	*x = DownloadUpdateRequest{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUpdateRequest) ProtoMessage() {}

func (x *DownloadUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUpdateRequest.ProtoReflect.Descriptor instead.
func (*DownloadUpdateRequest) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{39}
}

func (x *DownloadUpdateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DownloadUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadUpdateResponse) Reset() {
	*x = DownloadUpdateResponse{}
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadUpdateResponse) ProtoMessage() {}

func (x *DownloadUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakwater_v1_breakwater_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadUpdateResponse.ProtoReflect.Descriptor instead.
func (*DownloadUpdateResponse) Descriptor() ([]byte, []int) {
	return file_breakwater_v1_breakwater_proto_rawDescGZIP(), []int{40}
}

func (x *DownloadUpdateResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_breakwater_v1_breakwater_proto protoreflect.FileDescriptor

const file_breakwater_v1_breakwater_proto_rawDesc = "" +
	"\n" +
	"\x1ebreakwater/v1/breakwater.proto\x12\rbreakwater.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x127\n" +
	"\n" +
	"agent_info\x18\x02 \x01(\v2\x18.breakwater.v1.AgentInfoR\tagentInfo\x12&\n" +
	"\x0fclient_cert_pem\x18\x03 \x01(\fR\rclientCertPem\"\xa5\x01\n" +
	"\x0eEnrollResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1f\n" +
	"\vhashing_key\x18\x02 \x01(\fR\n" +
	"hashingKey\x126\n" +
	"\x17server_cert_fingerprint\x18\x03 \x01(\tR\x15serverCertFingerprint\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\"\x8f\x01\n" +
	"\tAgentInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\"\xba\x02\n" +
	"\rAgentToServer\x12,\n" +
	"\x05hello\x18\x01 \x01(\v2\x14.breakwater.v1.HelloH\x00R\x05hello\x128\n" +
	"\theartbeat\x18\x02 \x01(\v2\x18.breakwater.v1.HeartbeatH\x00R\theartbeat\x12?\n" +
	"\fjob_progress\x18\x03 \x01(\v2\x1a.breakwater.v1.JobProgressH\x00R\vjobProgress\x129\n" +
	"\n" +
	"job_result\x18\x04 \x01(\v2\x18.breakwater.v1.JobResultH\x00R\tjobResult\x12>\n" +
	"\tinventory\x18\x05 \x01(\v2\x1e.breakwater.v1.InventoryReportH\x00R\tinventoryB\x05\n" +
	"\x03msg\"\xc6\x02\n" +
	"\rServerToAgent\x126\n" +
	"\thello_ack\x18\x01 \x01(\v2\x17.breakwater.v1.HelloAckH\x00R\bhelloAck\x126\n" +
	"\tjob_start\x18\x02 \x01(\v2\x17.breakwater.v1.JobStartH\x00R\bjobStart\x129\n" +
	"\n" +
	"job_cancel\x18\x03 \x01(\v2\x18.breakwater.v1.JobCancelH\x00R\tjobCancel\x12?\n" +
	"\fupdate_offer\x18\x04 \x01(\v2\x1a.breakwater.v1.UpdateOfferH\x00R\vupdateOffer\x12B\n" +
	"\rheartbeat_ack\x18\x05 \x01(\v2\x1b.breakwater.v1.HeartbeatAckH\x00R\fheartbeatAckB\x05\n" +
	"\x03msg\"n\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12!\n" +
	"\fresume_token\x18\x03 \x01(\tR\vresumeToken\"\x8d\x01\n" +
	"\bHelloAck\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"g\n" +
	"\tHeartbeat\x12;\n" +
	"\vclient_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"clientTime\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x02 \x01(\x03R\tfreeBytes\"K\n" +
	"\fHeartbeatAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"n\n" +
	"\bJobStart\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.breakwater.v1.JobTypeR\x04type\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\fR\n" +
	"paramsJson\":\n" +
	"\tJobCancel\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xae\x01\n" +
	"\vJobProgress\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x02 \x01(\x03R\tbytesDone\x12\x1f\n" +
	"\vbytes_total\x18\x03 \x01(\x03R\n" +
	"bytesTotal\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x18\n" +
	"\apercent\x18\x06 \x01(\rR\apercent\"\xe7\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x04 \x01(\x03R\tbytesRead\x12!\n" +
	"\fbytes_stored\x18\x05 \x01(\x03R\vbytesStored\x12\x1f\n" +
	"\vsnapshot_id\x18\x06 \x01(\tR\n" +
	"snapshotId\x12!\n" +
	"\fresume_token\x18\a \x01(\tR\vresumeToken\"o\n" +
	"\x0fInventoryReport\x123\n" +
	"\avolumes\x18\x01 \x03(\v2\x19.breakwater.v1.VolumeInfoR\avolumes\x12'\n" +
	"\x03vms\x18\x02 \x03(\v2\x15.breakwater.v1.VMInfoR\x03vms\"j\n" +
	"\n" +
	"VolumeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mount\x18\x02 \x01(\tR\x05mount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x17\n" +
	"\afs_type\x18\x04 \x01(\tR\x06fsType\"c\n" +
	"\x06VMInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vrct_capable\x18\x03 \x01(\bR\n" +
	"rctCapable\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\x95\x01\n" +
	"\vUpdateOffer\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12+\n" +
	"\x11ed25519_signature\x18\x03 \x01(\fR\x10ed25519Signature\x12\x1c\n" +
	"\tmandatory\x18\x04 \x01(\bR\tmandatory\"N\n" +
	"\x14CheckContentsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vcontent_ids\x18\x02 \x03(\tR\n" +
	"contentIds\">\n" +
	"\x15CheckContentsResponse\x12%\n" +
	"\x0epresent_bitmap\x18\x01 \x01(\fR\rpresentBitmap\"p\n" +
	"\x12PutContentsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\"\x8e\x01\n" +
	"\x13PutContentsResponse\x12\x17\n" +
	"\aack_seq\x18\x01 \x01(\x04R\x06ackSeq\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"content_id\x18\x04 \x01(\tR\tcontentId\"J\n" +
	"\x14PutTreeObjectRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttree_json\x18\x02 \x01(\fR\btreeJson\"4\n" +
	"\x15PutTreeObjectResponse\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"U\n" +
	"\x17PutImageManifestRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rmanifest_json\x18\x02 \x01(\fR\fmanifestJson\"7\n" +
	"\x18PutImageManifestResponse\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"\xd7\x02\n" +
	"\x15CommitSnapshotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.breakwater.v1.SnapshotKindR\x04kind\x12$\n" +
	"\x0eroot_object_id\x18\x03 \x01(\tR\frootObjectId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\a \x01(\x03R\tbytesRead\x12!\n" +
	"\fbytes_stored\x18\b \x01(\x03R\vbytesStored\"\\\n" +
	"\x16CommitSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12!\n" +
	"\fmanifest_ref\x18\x02 \x01(\tR\vmanifestRef\"5\n" +
	"\x12GetSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"\xff\x01\n" +
	"\x13GetSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.breakwater.v1.SnapshotKindR\x04kind\x12$\n" +
	"\x0eroot_object_id\x18\x03 \x01(\tR\frootObjectId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x06 \x01(\tR\tmachineId\"/\n" +
	"\x10GetObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\"'\n" +
	"\x11GetObjectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"g\n" +
	"\x16GetContentRangeRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"-\n" +
	"\x17GetContentRangeResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"j\n" +
	"\x14ListSnapshotsRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x81\x01\n" +
	"\x15ListSnapshotsResponse\x12@\n" +
	"\tsnapshots\x18\x01 \x03(\v2\".breakwater.v1.GetSnapshotResponseR\tsnapshots\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"h\n" +
	"\x19ListSnapshotsSinceRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x7f\n" +
	"\x1aListSnapshotsSinceResponse\x12@\n" +
	"\tsnapshots\x18\x01 \x03(\v2\".breakwater.v1.GetSnapshotResponseR\tsnapshots\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"W\n" +
	"\x12CheckUpdateRequest\x12'\n" +
	"\x0fcurrent_version\x18\x01 \x01(\tR\x0ecurrentVersion\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\xb8\x01\n" +
	"\x13CheckUpdateResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12+\n" +
	"\x11ed25519_signature\x18\x03 \x01(\fR\x10ed25519Signature\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"sha256_hex\x18\x05 \x01(\tR\tsha256Hex\"1\n" +
	"\x15DownloadUpdateRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\".\n" +
	"\x16DownloadUpdateResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk*\x9f\x01\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14JOB_TYPE_FILE_BACKUP\x10\x01\x12\x19\n" +
	"\x15JOB_TYPE_IMAGE_BACKUP\x10\x02\x12\x1a\n" +
	"\x16JOB_TYPE_HYPERV_BACKUP\x10\x03\x12\x14\n" +
	"\x10JOB_TYPE_RESTORE\x10\x04\x12\x13\n" +
	"\x0fJOB_TYPE_UPDATE\x10\x05*x\n" +
	"\fSnapshotKind\x12\x1d\n" +
	"\x19SNAPSHOT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SNAPSHOT_KIND_FILE\x10\x01\x12\x17\n" +
	"\x13SNAPSHOT_KIND_IMAGE\x10\x02\x12\x18\n" +
	"\x14SNAPSHOT_KIND_HYPERV\x10\x032Z\n" +
	"\x11EnrollmentService\x12E\n" +
	"\x06Enroll\x12\x1c.breakwater.v1.EnrollRequest\x1a\x1d.breakwater.v1.EnrollResponse2[\n" +
	"\x0eControlService\x12I\n" +
	"\aChannel\x12\x1c.breakwater.v1.AgentToServer\x1a\x1c.breakwater.v1.ServerToAgent(\x010\x012\xe3\x03\n" +
	"\vDataService\x12Z\n" +
	"\rCheckContents\x12#.breakwater.v1.CheckContentsRequest\x1a$.breakwater.v1.CheckContentsResponse\x12X\n" +
	"\vPutContents\x12!.breakwater.v1.PutContentsRequest\x1a\".breakwater.v1.PutContentsResponse(\x010\x01\x12Z\n" +
	"\rPutTreeObject\x12#.breakwater.v1.PutTreeObjectRequest\x1a$.breakwater.v1.PutTreeObjectResponse\x12c\n" +
	"\x10PutImageManifest\x12&.breakwater.v1.PutImageManifestRequest\x1a'.breakwater.v1.PutImageManifestResponse\x12]\n" +
	"\x0eCommitSnapshot\x12$.breakwater.v1.CommitSnapshotRequest\x1a%.breakwater.v1.CommitSnapshotResponse2\xf8\x02\n" +
	"\x0eRestoreService\x12T\n" +
	"\vGetSnapshot\x12!.breakwater.v1.GetSnapshotRequest\x1a\".breakwater.v1.GetSnapshotResponse\x12P\n" +
	"\tGetObject\x12\x1f.breakwater.v1.GetObjectRequest\x1a .breakwater.v1.GetObjectResponse0\x01\x12b\n" +
	"\x0fGetContentRange\x12%.breakwater.v1.GetContentRangeRequest\x1a&.breakwater.v1.GetContentRangeResponse0\x01\x12Z\n" +
	"\rListSnapshots\x12#.breakwater.v1.ListSnapshotsRequest\x1a$.breakwater.v1.ListSnapshotsResponse2\x7f\n" +
	"\x12ReplicationService\x12i\n" +
	"\x12ListSnapshotsSince\x12(.breakwater.v1.ListSnapshotsSinceRequest\x1a).breakwater.v1.ListSnapshotsSinceResponse2\xc6\x01\n" +
	"\rUpdateService\x12T\n" +
	"\vCheckUpdate\x12!.breakwater.v1.CheckUpdateRequest\x1a\".breakwater.v1.CheckUpdateResponse\x12_\n" +
	"\x0eDownloadUpdate\x12$.breakwater.v1.DownloadUpdateRequest\x1a%.breakwater.v1.DownloadUpdateResponse0\x01BNZLgithub.com/ajthom90/breakwater/pkg/proto/breakwater/v1;breakwaterv1b\x06proto3"

var (
	file_breakwater_v1_breakwater_proto_rawDescOnce sync.Once
	file_breakwater_v1_breakwater_proto_rawDescData []byte
)

func file_breakwater_v1_breakwater_proto_rawDescGZIP() []byte {
	file_breakwater_v1_breakwater_proto_rawDescOnce.Do(func() {
		file_breakwater_v1_breakwater_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_breakwater_v1_breakwater_proto_rawDesc), len(file_breakwater_v1_breakwater_proto_rawDesc)))
	})
	return file_breakwater_v1_breakwater_proto_rawDescData
}

var file_breakwater_v1_breakwater_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_breakwater_v1_breakwater_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_breakwater_v1_breakwater_proto_goTypes = []any{
	(JobType)(0),                       // 0: breakwater.v1.JobType
	(SnapshotKind)(0),                  // 1: breakwater.v1.SnapshotKind
	(*EnrollRequest)(nil),              // 2: breakwater.v1.EnrollRequest
	(*EnrollResponse)(nil),             // 3: breakwater.v1.EnrollResponse
	(*AgentInfo)(nil),                  // 4: breakwater.v1.AgentInfo
	(*AgentToServer)(nil),              // 5: breakwater.v1.AgentToServer
	(*ServerToAgent)(nil),              // 6: breakwater.v1.ServerToAgent
	(*Hello)(nil),                      // 7: breakwater.v1.Hello
	(*HelloAck)(nil),                   // 8: breakwater.v1.HelloAck
	(*Heartbeat)(nil),                  // 9: breakwater.v1.Heartbeat
	(*HeartbeatAck)(nil),               // 10: breakwater.v1.HeartbeatAck
	(*JobStart)(nil),                   // 11: breakwater.v1.JobStart
	(*JobCancel)(nil),                  // 12: breakwater.v1.JobCancel
	(*JobProgress)(nil),                // 13: breakwater.v1.JobProgress
	(*JobResult)(nil),                  // 14: breakwater.v1.JobResult
	(*InventoryReport)(nil),            // 15: breakwater.v1.InventoryReport
	(*VolumeInfo)(nil),                 // 16: breakwater.v1.VolumeInfo
	(*VMInfo)(nil),                     // 17: breakwater.v1.VMInfo
	(*UpdateOffer)(nil),                // 18: breakwater.v1.UpdateOffer
	(*CheckContentsRequest)(nil),       // 19: breakwater.v1.CheckContentsRequest
	(*CheckContentsResponse)(nil),      // 20: breakwater.v1.CheckContentsResponse
	(*PutContentsRequest)(nil),         // 21: breakwater.v1.PutContentsRequest
	(*PutContentsResponse)(nil),        // 22: breakwater.v1.PutContentsResponse
	(*PutTreeObjectRequest)(nil),       // 23: breakwater.v1.PutTreeObjectRequest
	(*PutTreeObjectResponse)(nil),      // 24: breakwater.v1.PutTreeObjectResponse
	(*PutImageManifestRequest)(nil),    // 25: breakwater.v1.PutImageManifestRequest
	(*PutImageManifestResponse)(nil),   // 26: breakwater.v1.PutImageManifestResponse
	(*CommitSnapshotRequest)(nil),      // 27: breakwater.v1.CommitSnapshotRequest
	(*CommitSnapshotResponse)(nil),     // 28: breakwater.v1.CommitSnapshotResponse
	(*GetSnapshotRequest)(nil),         // 29: breakwater.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),        // 30: breakwater.v1.GetSnapshotResponse
	(*GetObjectRequest)(nil),           // 31: breakwater.v1.GetObjectRequest
	(*GetObjectResponse)(nil),          // 32: breakwater.v1.GetObjectResponse
	(*GetContentRangeRequest)(nil),     // 33: breakwater.v1.GetContentRangeRequest
	(*GetContentRangeResponse)(nil),    // 34: breakwater.v1.GetContentRangeResponse
	(*ListSnapshotsRequest)(nil),       // 35: breakwater.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),      // 36: breakwater.v1.ListSnapshotsResponse
	(*ListSnapshotsSinceRequest)(nil),  // 37: breakwater.v1.ListSnapshotsSinceRequest
	(*ListSnapshotsSinceResponse)(nil), // 38: breakwater.v1.ListSnapshotsSinceResponse
	(*CheckUpdateRequest)(nil),         // 39: breakwater.v1.CheckUpdateRequest
	(*CheckUpdateResponse)(nil),        // 40: breakwater.v1.CheckUpdateResponse
	(*DownloadUpdateRequest)(nil),      // 41: breakwater.v1.DownloadUpdateRequest
	(*DownloadUpdateResponse)(nil),     // 42: breakwater.v1.DownloadUpdateResponse
	(*timestamppb.Timestamp)(nil),      // 43: google.protobuf.Timestamp
}
var file_breakwater_v1_breakwater_proto_depIdxs = []int32{
	4,  // 0: breakwater.v1.EnrollRequest.agent_info:type_name -> breakwater.v1.AgentInfo
	7,  // 1: breakwater.v1.AgentToServer.hello:type_name -> breakwater.v1.Hello
	9,  // 2: breakwater.v1.AgentToServer.heartbeat:type_name -> breakwater.v1.Heartbeat
	13, // 3: breakwater.v1.AgentToServer.job_progress:type_name -> breakwater.v1.JobProgress
	14, // 4: breakwater.v1.AgentToServer.job_result:type_name -> breakwater.v1.JobResult
	15, // 5: breakwater.v1.AgentToServer.inventory:type_name -> breakwater.v1.InventoryReport
	8,  // 6: breakwater.v1.ServerToAgent.hello_ack:type_name -> breakwater.v1.HelloAck
	11, // 7: breakwater.v1.ServerToAgent.job_start:type_name -> breakwater.v1.JobStart
	12, // 8: breakwater.v1.ServerToAgent.job_cancel:type_name -> breakwater.v1.JobCancel
	18, // 9: breakwater.v1.ServerToAgent.update_offer:type_name -> breakwater.v1.UpdateOffer
	10, // 10: breakwater.v1.ServerToAgent.heartbeat_ack:type_name -> breakwater.v1.HeartbeatAck
	43, // 11: breakwater.v1.HelloAck.server_time:type_name -> google.protobuf.Timestamp
	43, // 12: breakwater.v1.Heartbeat.client_time:type_name -> google.protobuf.Timestamp
	43, // 13: breakwater.v1.HeartbeatAck.server_time:type_name -> google.protobuf.Timestamp
	0,  // 14: breakwater.v1.JobStart.type:type_name -> breakwater.v1.JobType
	16, // 15: breakwater.v1.InventoryReport.volumes:type_name -> breakwater.v1.VolumeInfo
	17, // 16: breakwater.v1.InventoryReport.vms:type_name -> breakwater.v1.VMInfo
	1,  // 17: breakwater.v1.CommitSnapshotRequest.kind:type_name -> breakwater.v1.SnapshotKind
	43, // 18: breakwater.v1.CommitSnapshotRequest.started_at:type_name -> google.protobuf.Timestamp
	43, // 19: breakwater.v1.CommitSnapshotRequest.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 20: breakwater.v1.GetSnapshotResponse.kind:type_name -> breakwater.v1.SnapshotKind
	43, // 21: breakwater.v1.GetSnapshotResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 22: breakwater.v1.ListSnapshotsResponse.snapshots:type_name -> breakwater.v1.GetSnapshotResponse
	30, // 23: breakwater.v1.ListSnapshotsSinceResponse.snapshots:type_name -> breakwater.v1.GetSnapshotResponse
	2,  // 24: breakwater.v1.EnrollmentService.Enroll:input_type -> breakwater.v1.EnrollRequest
	5,  // 25: breakwater.v1.ControlService.Channel:input_type -> breakwater.v1.AgentToServer
	19, // 26: breakwater.v1.DataService.CheckContents:input_type -> breakwater.v1.CheckContentsRequest
	21, // 27: breakwater.v1.DataService.PutContents:input_type -> breakwater.v1.PutContentsRequest
	23, // 28: breakwater.v1.DataService.PutTreeObject:input_type -> breakwater.v1.PutTreeObjectRequest
	25, // 29: breakwater.v1.DataService.PutImageManifest:input_type -> breakwater.v1.PutImageManifestRequest
	27, // 30: breakwater.v1.DataService.CommitSnapshot:input_type -> breakwater.v1.CommitSnapshotRequest
	29, // 31: breakwater.v1.RestoreService.GetSnapshot:input_type -> breakwater.v1.GetSnapshotRequest
	31, // 32: breakwater.v1.RestoreService.GetObject:input_type -> breakwater.v1.GetObjectRequest
	33, // 33: breakwater.v1.RestoreService.GetContentRange:input_type -> breakwater.v1.GetContentRangeRequest
	35, // 34: breakwater.v1.RestoreService.ListSnapshots:input_type -> breakwater.v1.ListSnapshotsRequest
	37, // 35: breakwater.v1.ReplicationService.ListSnapshotsSince:input_type -> breakwater.v1.ListSnapshotsSinceRequest
	39, // 36: breakwater.v1.UpdateService.CheckUpdate:input_type -> breakwater.v1.CheckUpdateRequest
	41, // 37: breakwater.v1.UpdateService.DownloadUpdate:input_type -> breakwater.v1.DownloadUpdateRequest
	3,  // 38: breakwater.v1.EnrollmentService.Enroll:output_type -> breakwater.v1.EnrollResponse
	6,  // 39: breakwater.v1.ControlService.Channel:output_type -> breakwater.v1.ServerToAgent
	20, // 40: breakwater.v1.DataService.CheckContents:output_type -> breakwater.v1.CheckContentsResponse
	22, // 41: breakwater.v1.DataService.PutContents:output_type -> breakwater.v1.PutContentsResponse
	24, // 42: breakwater.v1.DataService.PutTreeObject:output_type -> breakwater.v1.PutTreeObjectResponse
	26, // 43: breakwater.v1.DataService.PutImageManifest:output_type -> breakwater.v1.PutImageManifestResponse
	28, // 44: breakwater.v1.DataService.CommitSnapshot:output_type -> breakwater.v1.CommitSnapshotResponse
	30, // 45: breakwater.v1.RestoreService.GetSnapshot:output_type -> breakwater.v1.GetSnapshotResponse
	32, // 46: breakwater.v1.RestoreService.GetObject:output_type -> breakwater.v1.GetObjectResponse
	34, // 47: breakwater.v1.RestoreService.GetContentRange:output_type -> breakwater.v1.GetContentRangeResponse
	36, // 48: breakwater.v1.RestoreService.ListSnapshots:output_type -> breakwater.v1.ListSnapshotsResponse
	38, // 49: breakwater.v1.ReplicationService.ListSnapshotsSince:output_type -> breakwater.v1.ListSnapshotsSinceResponse
	40, // 50: breakwater.v1.UpdateService.CheckUpdate:output_type -> breakwater.v1.CheckUpdateResponse
	42, // 51: breakwater.v1.UpdateService.DownloadUpdate:output_type -> breakwater.v1.DownloadUpdateResponse
	38, // [38:52] is the sub-list for method output_type
	24, // [24:38] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_breakwater_v1_breakwater_proto_init() }
func file_breakwater_v1_breakwater_proto_init() {
	if File_breakwater_v1_breakwater_proto != nil {
		return
	}
	file_breakwater_v1_breakwater_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentToServer_Hello)(nil),
		(*AgentToServer_Heartbeat)(nil),
		(*AgentToServer_JobProgress)(nil),
		(*AgentToServer_JobResult)(nil),
		(*AgentToServer_Inventory)(nil),
	}
	file_breakwater_v1_breakwater_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerToAgent_HelloAck)(nil),
		(*ServerToAgent_JobStart)(nil),
		(*ServerToAgent_JobCancel)(nil),
		(*ServerToAgent_UpdateOffer)(nil),
		(*ServerToAgent_HeartbeatAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_breakwater_v1_breakwater_proto_rawDesc), len(file_breakwater_v1_breakwater_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_breakwater_v1_breakwater_proto_goTypes,
		DependencyIndexes: file_breakwater_v1_breakwater_proto_depIdxs,
		EnumInfos:         file_breakwater_v1_breakwater_proto_enumTypes,
		MessageInfos:      file_breakwater_v1_breakwater_proto_msgTypes,
	}.Build()
	File_breakwater_v1_breakwater_proto = out.File
	file_breakwater_v1_breakwater_proto_goTypes = nil
	file_breakwater_v1_breakwater_proto_depIdxs = nil
}
