// Breakwater agent/replication wire contract.
// Frozen for M1 — additive changes only after this milestone.
// See PLAN.md → Transport & protocol.
//
// Append-only is structural: NO RPC on the agent port deletes, prunes, or
// mutates retention. Those exist only on the human-authenticated web/REST port.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: breakwater/v1/breakwater.proto

package breakwaterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentService_Enroll_FullMethodName = "/breakwater.v1.EnrollmentService/Enroll"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrollmentServiceClient interface {
	// Enroll exchanges a one-time enrollment token for a machine identity.
	// Client presents a self-signed cert; server verifies the token embeds the
	// server cert fingerprint (zero TOFU) and binds agent cert FP → machine row.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
type EnrollmentServiceServer interface {
	// Enroll exchanges a one-time enrollment token for a machine identity.
	// Client presents a self-signed cert; server verifies the token embeds the
	// server cert fingerprint (zero TOFU) and binds agent cert FP → machine row.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakwater.v1.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _EnrollmentService_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breakwater/v1/breakwater.proto",
}

const (
	ControlService_Channel_FullMethodName = "/breakwater.v1.ControlService/Channel"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	// Channel is the persistent agent control plane: keepalives, job dispatch,
	// inventory, progress. Idempotent reconnect/resume.
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToServer, ServerToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_ChannelClient = grpc.BidiStreamingClient[AgentToServer, ServerToAgent]

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	// Channel is the persistent agent control plane: keepalives, job dispatch,
	// inventory, progress. Idempotent reconnect/resume.
	Channel(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) Channel(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error {
	return status.Error(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).Channel(&grpc.GenericServerStream[AgentToServer, ServerToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_ChannelServer = grpc.BidiStreamingServer[AgentToServer, ServerToAgent]

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakwater.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _ControlService_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "breakwater/v1/breakwater.proto",
}

const (
	DataService_CheckContents_FullMethodName    = "/breakwater.v1.DataService/CheckContents"
	DataService_PutContents_FullMethodName      = "/breakwater.v1.DataService/PutContents"
	DataService_PutTreeObject_FullMethodName    = "/breakwater.v1.DataService/PutTreeObject"
	DataService_PutImageManifest_FullMethodName = "/breakwater.v1.DataService/PutImageManifest"
	DataService_CommitSnapshot_FullMethodName   = "/breakwater.v1.DataService/CommitSnapshot"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	// CheckContents is the have/want handshake. Batches of up to 4096 IDs.
	CheckContents(ctx context.Context, in *CheckContentsRequest, opts ...grpc.CallOption) (*CheckContentsResponse, error)
	// PutContents streams content payloads; server re-hashes and rejects mismatches.
	PutContents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PutContentsRequest, PutContentsResponse], error)
	// PutTreeObject stores a directory tree object (JSON).
	PutTreeObject(ctx context.Context, in *PutTreeObjectRequest, opts ...grpc.CallOption) (*PutTreeObjectResponse, error)
	// PutImageManifest stores a fixed-block image manifest (later phases).
	PutImageManifest(ctx context.Context, in *PutImageManifestRequest, opts ...grpc.CallOption) (*PutImageManifestResponse, error)
	// CommitSnapshot finalizes a snapshot record after all contents/objects are present.
	CommitSnapshot(ctx context.Context, in *CommitSnapshotRequest, opts ...grpc.CallOption) (*CommitSnapshotResponse, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) CheckContents(ctx context.Context, in *CheckContentsRequest, opts ...grpc.CallOption) (*CheckContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckContentsResponse)
	err := c.cc.Invoke(ctx, DataService_CheckContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) PutContents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PutContentsRequest, PutContentsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_PutContents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutContentsRequest, PutContentsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_PutContentsClient = grpc.BidiStreamingClient[PutContentsRequest, PutContentsResponse]

func (c *dataServiceClient) PutTreeObject(ctx context.Context, in *PutTreeObjectRequest, opts ...grpc.CallOption) (*PutTreeObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutTreeObjectResponse)
	err := c.cc.Invoke(ctx, DataService_PutTreeObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) PutImageManifest(ctx context.Context, in *PutImageManifestRequest, opts ...grpc.CallOption) (*PutImageManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutImageManifestResponse)
	err := c.cc.Invoke(ctx, DataService_PutImageManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) CommitSnapshot(ctx context.Context, in *CommitSnapshotRequest, opts ...grpc.CallOption) (*CommitSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitSnapshotResponse)
	err := c.cc.Invoke(ctx, DataService_CommitSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	// CheckContents is the have/want handshake. Batches of up to 4096 IDs.
	CheckContents(context.Context, *CheckContentsRequest) (*CheckContentsResponse, error)
	// PutContents streams content payloads; server re-hashes and rejects mismatches.
	PutContents(grpc.BidiStreamingServer[PutContentsRequest, PutContentsResponse]) error
	// PutTreeObject stores a directory tree object (JSON).
	PutTreeObject(context.Context, *PutTreeObjectRequest) (*PutTreeObjectResponse, error)
	// PutImageManifest stores a fixed-block image manifest (later phases).
	PutImageManifest(context.Context, *PutImageManifestRequest) (*PutImageManifestResponse, error)
	// CommitSnapshot finalizes a snapshot record after all contents/objects are present.
	CommitSnapshot(context.Context, *CommitSnapshotRequest) (*CommitSnapshotResponse, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) CheckContents(context.Context, *CheckContentsRequest) (*CheckContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckContents not implemented")
}
func (UnimplementedDataServiceServer) PutContents(grpc.BidiStreamingServer[PutContentsRequest, PutContentsResponse]) error {
	return status.Error(codes.Unimplemented, "method PutContents not implemented")
}
func (UnimplementedDataServiceServer) PutTreeObject(context.Context, *PutTreeObjectRequest) (*PutTreeObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutTreeObject not implemented")
}
func (UnimplementedDataServiceServer) PutImageManifest(context.Context, *PutImageManifestRequest) (*PutImageManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutImageManifest not implemented")
}
func (UnimplementedDataServiceServer) CommitSnapshot(context.Context, *CommitSnapshotRequest) (*CommitSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitSnapshot not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_CheckContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CheckContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_CheckContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CheckContents(ctx, req.(*CheckContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_PutContents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).PutContents(&grpc.GenericServerStream[PutContentsRequest, PutContentsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_PutContentsServer = grpc.BidiStreamingServer[PutContentsRequest, PutContentsResponse]

func _DataService_PutTreeObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTreeObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).PutTreeObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_PutTreeObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).PutTreeObject(ctx, req.(*PutTreeObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_PutImageManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutImageManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).PutImageManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_PutImageManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).PutImageManifest(ctx, req.(*PutImageManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_CommitSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CommitSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_CommitSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CommitSnapshot(ctx, req.(*CommitSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakwater.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckContents",
			Handler:    _DataService_CheckContents_Handler,
		},
		{
			MethodName: "PutTreeObject",
			Handler:    _DataService_PutTreeObject_Handler,
		},
		{
			MethodName: "PutImageManifest",
			Handler:    _DataService_PutImageManifest_Handler,
		},
		{
			MethodName: "CommitSnapshot",
			Handler:    _DataService_CommitSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutContents",
			Handler:       _DataService_PutContents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "breakwater/v1/breakwater.proto",
}

const (
	RestoreService_GetSnapshot_FullMethodName     = "/breakwater.v1.RestoreService/GetSnapshot"
	RestoreService_GetObject_FullMethodName       = "/breakwater.v1.RestoreService/GetObject"
	RestoreService_GetContentRange_FullMethodName = "/breakwater.v1.RestoreService/GetContentRange"
	RestoreService_ListSnapshots_FullMethodName   = "/breakwater.v1.RestoreService/ListSnapshots"
)

// RestoreServiceClient is the client API for RestoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestoreServiceClient interface {
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error)
	GetContentRange(ctx context.Context, in *GetContentRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetContentRangeResponse], error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
}

type restoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestoreServiceClient(cc grpc.ClientConnInterface) RestoreServiceClient {
	return &restoreServiceClient{cc}
}

func (c *restoreServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, RestoreService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoreServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RestoreService_ServiceDesc.Streams[0], RestoreService_GetObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectRequest, GetObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RestoreService_GetObjectClient = grpc.ServerStreamingClient[GetObjectResponse]

func (c *restoreServiceClient) GetContentRange(ctx context.Context, in *GetContentRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetContentRangeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RestoreService_ServiceDesc.Streams[1], RestoreService_GetContentRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetContentRangeRequest, GetContentRangeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RestoreService_GetContentRangeClient = grpc.ServerStreamingClient[GetContentRangeResponse]

func (c *restoreServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, RestoreService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestoreServiceServer is the server API for RestoreService service.
// All implementations must embed UnimplementedRestoreServiceServer
// for forward compatibility.
type RestoreServiceServer interface {
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error
	GetContentRange(*GetContentRangeRequest, grpc.ServerStreamingServer[GetContentRangeResponse]) error
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	mustEmbedUnimplementedRestoreServiceServer()
}

// UnimplementedRestoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestoreServiceServer struct{}

func (UnimplementedRestoreServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedRestoreServiceServer) GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error {
	return status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedRestoreServiceServer) GetContentRange(*GetContentRangeRequest, grpc.ServerStreamingServer[GetContentRangeResponse]) error {
	return status.Error(codes.Unimplemented, "method GetContentRange not implemented")
}
func (UnimplementedRestoreServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedRestoreServiceServer) mustEmbedUnimplementedRestoreServiceServer() {}
func (UnimplementedRestoreServiceServer) testEmbeddedByValue()                        {}

// UnsafeRestoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestoreServiceServer will
// result in compilation errors.
type UnsafeRestoreServiceServer interface {
	mustEmbedUnimplementedRestoreServiceServer()
}

func RegisterRestoreServiceServer(s grpc.ServiceRegistrar, srv RestoreServiceServer) {
	// If the following call panics, it indicates UnimplementedRestoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestoreService_ServiceDesc, srv)
}

func _RestoreService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoreService_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestoreServiceServer).GetObject(m, &grpc.GenericServerStream[GetObjectRequest, GetObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RestoreService_GetObjectServer = grpc.ServerStreamingServer[GetObjectResponse]

func _RestoreService_GetContentRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetContentRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestoreServiceServer).GetContentRange(m, &grpc.GenericServerStream[GetContentRangeRequest, GetContentRangeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RestoreService_GetContentRangeServer = grpc.ServerStreamingServer[GetContentRangeResponse]

func _RestoreService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoreServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RestoreService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoreServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestoreService_ServiceDesc is the grpc.ServiceDesc for RestoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakwater.v1.RestoreService",
	HandlerType: (*RestoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _RestoreService_GetSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _RestoreService_ListSnapshots_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetObject",
			Handler:       _RestoreService_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetContentRange",
			Handler:       _RestoreService_GetContentRange_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "breakwater/v1/breakwater.proto",
}

const (
	ReplicationService_ListSnapshotsSince_FullMethodName = "/breakwater.v1.ReplicationService/ListSnapshotsSince"
)

// ReplicationServiceClient is the client API for ReplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationServiceClient interface {
	// ListSnapshotsSince returns snapshot records after a cursor for a mirrored repo.
	ListSnapshotsSince(ctx context.Context, in *ListSnapshotsSinceRequest, opts ...grpc.CallOption) (*ListSnapshotsSinceResponse, error)
}

type replicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationServiceClient(cc grpc.ClientConnInterface) ReplicationServiceClient {
	return &replicationServiceClient{cc}
}

func (c *replicationServiceClient) ListSnapshotsSince(ctx context.Context, in *ListSnapshotsSinceRequest, opts ...grpc.CallOption) (*ListSnapshotsSinceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsSinceResponse)
	err := c.cc.Invoke(ctx, ReplicationService_ListSnapshotsSince_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationServiceServer is the server API for ReplicationService service.
// All implementations must embed UnimplementedReplicationServiceServer
// for forward compatibility.
type ReplicationServiceServer interface {
	// ListSnapshotsSince returns snapshot records after a cursor for a mirrored repo.
	ListSnapshotsSince(context.Context, *ListSnapshotsSinceRequest) (*ListSnapshotsSinceResponse, error)
	mustEmbedUnimplementedReplicationServiceServer()
}

// UnimplementedReplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplicationServiceServer struct{}

func (UnimplementedReplicationServiceServer) ListSnapshotsSince(context.Context, *ListSnapshotsSinceRequest) (*ListSnapshotsSinceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshotsSince not implemented")
}
func (UnimplementedReplicationServiceServer) mustEmbedUnimplementedReplicationServiceServer() {}
func (UnimplementedReplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeReplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationServiceServer will
// result in compilation errors.
type UnsafeReplicationServiceServer interface {
	mustEmbedUnimplementedReplicationServiceServer()
}

func RegisterReplicationServiceServer(s grpc.ServiceRegistrar, srv ReplicationServiceServer) {
	// If the following call panics, it indicates UnimplementedReplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplicationService_ServiceDesc, srv)
}

func _ReplicationService_ListSnapshotsSince_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsSinceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationServiceServer).ListSnapshotsSince(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationService_ListSnapshotsSince_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationServiceServer).ListSnapshotsSince(ctx, req.(*ListSnapshotsSinceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicationService_ServiceDesc is the grpc.ServiceDesc for ReplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakwater.v1.ReplicationService",
	HandlerType: (*ReplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSnapshotsSince",
			Handler:    _ReplicationService_ListSnapshotsSince_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breakwater/v1/breakwater.proto",
}

const (
	UpdateService_CheckUpdate_FullMethodName    = "/breakwater.v1.UpdateService/CheckUpdate"
	UpdateService_DownloadUpdate_FullMethodName = "/breakwater.v1.UpdateService/DownloadUpdate"
)

// UpdateServiceClient is the client API for UpdateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateServiceClient interface {
	CheckUpdate(ctx context.Context, in *CheckUpdateRequest, opts ...grpc.CallOption) (*CheckUpdateResponse, error)
	DownloadUpdate(ctx context.Context, in *DownloadUpdateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadUpdateResponse], error)
}

type updateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateServiceClient(cc grpc.ClientConnInterface) UpdateServiceClient {
	return &updateServiceClient{cc}
}

func (c *updateServiceClient) CheckUpdate(ctx context.Context, in *CheckUpdateRequest, opts ...grpc.CallOption) (*CheckUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUpdateResponse)
	err := c.cc.Invoke(ctx, UpdateService_CheckUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateServiceClient) DownloadUpdate(ctx context.Context, in *DownloadUpdateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadUpdateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpdateService_ServiceDesc.Streams[0], UpdateService_DownloadUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadUpdateRequest, DownloadUpdateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdateService_DownloadUpdateClient = grpc.ServerStreamingClient[DownloadUpdateResponse]

// UpdateServiceServer is the server API for UpdateService service.
// All implementations must embed UnimplementedUpdateServiceServer
// for forward compatibility.
type UpdateServiceServer interface {
	CheckUpdate(context.Context, *CheckUpdateRequest) (*CheckUpdateResponse, error)
	DownloadUpdate(*DownloadUpdateRequest, grpc.ServerStreamingServer[DownloadUpdateResponse]) error
	mustEmbedUnimplementedUpdateServiceServer()
}

// UnimplementedUpdateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateServiceServer struct{}

func (UnimplementedUpdateServiceServer) CheckUpdate(context.Context, *CheckUpdateRequest) (*CheckUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUpdate not implemented")
}
func (UnimplementedUpdateServiceServer) DownloadUpdate(*DownloadUpdateRequest, grpc.ServerStreamingServer[DownloadUpdateResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadUpdate not implemented")
}
func (UnimplementedUpdateServiceServer) mustEmbedUnimplementedUpdateServiceServer() {}
func (UnimplementedUpdateServiceServer) testEmbeddedByValue()                       {}

// UnsafeUpdateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateServiceServer will
// result in compilation errors.
type UnsafeUpdateServiceServer interface {
	mustEmbedUnimplementedUpdateServiceServer()
}

func RegisterUpdateServiceServer(s grpc.ServiceRegistrar, srv UpdateServiceServer) {
	// If the following call panics, it indicates UnimplementedUpdateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateService_ServiceDesc, srv)
}

func _UpdateService_CheckUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateServiceServer).CheckUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateService_CheckUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateServiceServer).CheckUpdate(ctx, req.(*CheckUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateService_DownloadUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadUpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdateServiceServer).DownloadUpdate(m, &grpc.GenericServerStream[DownloadUpdateRequest, DownloadUpdateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpdateService_DownloadUpdateServer = grpc.ServerStreamingServer[DownloadUpdateResponse]

// UpdateService_ServiceDesc is the grpc.ServiceDesc for UpdateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakwater.v1.UpdateService",
	HandlerType: (*UpdateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUpdate",
			Handler:    _UpdateService_CheckUpdate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadUpdate",
			Handler:       _UpdateService_DownloadUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "breakwater/v1/breakwater.proto",
}
